import os
import zipfile
import io
import csv
from io import BytesIO
from fpdf import FPDF
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.style import WD_STYLE_TYPE
import datetime

# --- Theme Definitions ---
THEMES = {
    "Professional": {
        "primary_color": (63, 81, 181),    # Indigo
        "text_color": (33, 33, 33),
        "font_family": "Arial",
        "bg_color": (255, 255, 255)
    },
    "Academic": {
        "primary_color": (33, 33, 33),     # Dark Grey
        "text_color": (0, 0, 0),
        "font_family": "Times",
        "bg_color": (255, 255, 255)
    },
    "Corporate": {
        "primary_color": (0, 51, 102),     # Navy Blue
        "text_color": (51, 51, 51),
        "font_family": "Arial",
        "bg_color": (255, 255, 255)
    },
    "Modern": {
        "primary_color": (0, 150, 136),    # Teal
        "text_color": (69, 90, 100),
        "font_family": "Arial",            # using Arial as standard FPDF fallback
        "bg_color": (250, 250, 250)
    },
    "Minimal": {
        "primary_color": (0, 0, 0),        # Black
        "text_color": (0, 0, 0),
        "font_family": "Arial",
        "bg_color": (255, 255, 255)
    }
}

class CustomExporterPDF(FPDF):
    def __init__(self, theme_name="Professional", title="AI Video Export"):
        super().__init__()
        self.theme = THEMES.get(theme_name, THEMES["Professional"])
        self.doc_title = title
        
    def header(self):
        self.set_font(self.theme["font_family"], 'B', 10)
        r, g, b = self.theme["primary_color"]
        self.set_text_color(r, g, b)
        self.cell(0, 10, self.doc_title, 0, 0, 'R')
        self.ln(10)
        self.set_draw_color(r, g, b)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font(self.theme["font_family"], 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')


def generate_combined_pdf(selected_sections, video_info, data_sources, theme_name="Professional"):
    """
    Generates a PDF incorporating selected sections.
    """
    pdf = CustomExporterPDF(theme_name=theme_name, title=f"Report: {video_info.get('title', 'Video')}")
    pdf.add_page()
    
    theme = pdf.theme
    
    # Cover Page
    pdf.set_font(theme["font_family"], 'B', 24)
    r, g, b = theme["primary_color"]
    pdf.set_text_color(r, g, b)
    pdf.ln(40)
    pdf.multi_cell(0, 10, video_info.get("title", "Untitled Video"), align='C')
    
    pdf.set_font(theme["font_family"], '', 14)
    pdf.set_text_color(*theme["text_color"])
    pdf.ln(10)
    pdf.cell(0, 10, f"Channel: {video_info.get('channel', 'Unknown')}", ln=True, align='C')
    pdf.cell(0, 10, f"Generated On: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    
    pdf.ln(40)
    pdf.set_font(theme["font_family"], 'I', 12)
    pdf.cell(0, 10, "Generated by AI Video Summarization App", ln=True, align='C')
    
    # Table of Contents
    pdf.add_page()
    pdf.set_font(theme["font_family"], 'B', 18)
    pdf.set_text_color(*theme["primary_color"])
    pdf.cell(0, 10, "Table of Contents", ln=True)
    pdf.ln(5)
    
    pdf.set_font(theme["font_family"], '', 12)
    pdf.set_text_color(*theme["text_color"])
    for section in selected_sections:
        pdf.cell(0, 8, f"- {section}", ln=True)
        
    # Content Sections
    for section in selected_sections:
        pdf.add_page()
        pdf.set_font(theme["font_family"], 'B', 18)
        pdf.set_text_color(*theme["primary_color"])
        pdf.cell(0, 10, section, ln=True)
        pdf.ln(5)
        
        pdf.set_font(theme["font_family"], '', 11)
        pdf.set_text_color(*theme["text_color"])
        content = data_sources.get(section, "No content available.")
        # Ensure utf-8 encoding compatibility
        content = content.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, content)
        
    pdf_bytes = pdf.output(dest='S').encode('latin-1')
    return pdf_bytes

def generate_combined_docx(selected_sections, video_info, data_sources, theme_name="Professional"):
    """
    Generates a DOCX file incorporating selected sections.
    """
    document = Document()
    theme = THEMES.get(theme_name, THEMES["Professional"])
    
    # Setup styles
    styles = document.styles
    title_style = styles['Title']
    font = title_style.font
    font.name = theme["font_family"]
    font.color.rgb = RGBColor(*theme["primary_color"])
    
    heading_style = styles['Heading 1']
    h_font = heading_style.font
    h_font.name = theme["font_family"]
    h_font.color.rgb = RGBColor(*theme["primary_color"])
    
    # Cover
    document.add_heading(video_info.get("title", "Untitled Video"), level=0)
    document.add_paragraph(f"Channel: {video_info.get('channel', 'Unknown')}")
    document.add_paragraph(f"Generated On: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
    document.add_page_break()
    
    # Table of Contents placeholder
    document.add_heading('Table of Contents', level=1)
    for section in selected_sections:
        document.add_paragraph(f"- {section}")
    document.add_page_break()
    
    # Content
    for section in selected_sections:
        document.add_heading(section, level=1)
        content = data_sources.get(section, "No content available.")
        document.add_paragraph(content)
        document.add_page_break()
        
    io_stream = BytesIO()
    document.save(io_stream)
    return io_stream.getvalue()

def generate_combined_txt(selected_sections, video_info, data_sources):
    """
    Generates plain text export.
    """
    lines = []
    lines.append("="*50)
    lines.append(f"Title: {video_info.get('title', 'Untitled Video')}")
    lines.append(f"Channel: {video_info.get('channel', 'Unknown')}")
    lines.append(f"Generated On: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("="*50)
    lines.append("\nTABLE OF CONTENTS:")
    for section in selected_sections:
        lines.append(f"- {section}")
    lines.append("\n" + "="*50)
    
    for section in selected_sections:
        lines.append(f"\n[{section.upper()}]")
        lines.append("-" * len(section))
        content = data_sources.get(section, "No content available.")
        lines.append(content)
        lines.append("\n" + "="*50)
        
    return "\n".join(lines).encode('utf-8')

def generate_zip_package(export_files, video_title="export"):
    """
    export_files: list of dicts like [{"filename": "summary.pdf", "data": bytes}]
    """
    zip_buffer = BytesIO()
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        for file in export_files:
            zip_file.writestr(file["filename"], file["data"])
    return zip_buffer.getvalue()

def generate_comparison_csv(comparison_markdown):
    """
    Parses a Markdown table and returns CSV bytes.
    """
    lines = comparison_markdown.strip().split('\n')
    if not lines:
        return b""
        
    csv_buffer = io.StringIO()
    writer = csv.writer(csv_buffer)
    
    for line in lines:
        line = line.strip()
        if not line.startswith('|'):
            continue
        # Check if it's a separator line (e.g., |---|---|)
        if set(line.replace('|', '').replace('-', '').replace(' ', '').replace(':', '')) == set():
            continue
            
        row = [cell.strip() for cell in line.split('|')[1:-1]]
        writer.writerow(row)
        
    return csv_buffer.getvalue().encode('utf-8')
